url: http://takeshape.io/
permalink : pretty
lang: en

exclude:
  - node_modules
  - package.json

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
