site_name: TakeShape
site_url: http://takeshape.io
site_description: Let your ideas...
author_name: Ronik Design 
author_email: info@ronikdesign.com
github_author_name: takeshape
github_author_url: https://github.com/takeshape
github_repo_name: takeshape
github_repo_url: https://github.com/takeshape/takeshape
